version: 2
models:
 - name: assets_stg
   description: "Staging table for crypto assets, read data from raw.assets and convert non string data to respective datatypes"
   columns:
      - name: asset_id
        description: "Unique identifier for the asset"
        tests:
              - not_null
      - name: name
        description: "Name of the asset"
        tests:
               - not_null
      - name: price_usd
        description: "Price of the coin"
        tests:
              - not_null
              - dbt_utils.expression_is_true:
                    expression: "> 0"
      - name: ingestion_timestamp
        description: "Timestamp when the data was loaded"
        tests:
              - not_null
              - dbt_utils.expression_is_true:
                  expression: "<= current_timestamp"
   tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
                - asset_id
                - ingestion_timestamp